name: daily_hof1

# Run this workflow every time a new commit pushed to your repository
on:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  run_23:
    # Name the Job
    name: run_23
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          GOTAUTH: ${{ secrets.GOTAUTH}}
        run: |
          cd ../../
          pwd
          git clone https://$GOTAUTH@github.com/brokenjade3000/got_auto.git
          cd got_auto
          chmod 775 ./script/install.sh
          ./script/install.sh
          
      # Runs the Super-Linter action
      - name: run_23
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
        run: |
          pwd
          cd /home/runner/work/got_auto/src
          python --version
          python run_daily_hof.py 2,3


 

  run_45:
    # Name the Job
    name: run_45
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          GOTAUTH: ${{ secrets.GOTAUTH}}
        run: |
          cd ../../
          pwd
          git clone https://$GOTAUTH@github.com/brokenjade3000/got_auto.git
          cd got_auto
          chmod 775 ./script/install.sh
          ./script/install.sh
          
      # Runs the Super-Linter action
      - name: run_45
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
        run: |
          pwd
          cd /home/runner/work/got_auto/src
          python --version
          python run_daily_hof.py 4,5         

            
  run_67:
    # Name the Job
    name: run_67
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          GOTAUTH: ${{ secrets.GOTAUTH}}
        run: |
          cd ../../
          pwd
          git clone https://$GOTAUTH@github.com/brokenjade3000/got_auto.git
          cd got_auto
          chmod 775 ./script/install.sh
          ./script/install.sh
          
      # Runs the Super-Linter action
      - name: run_67
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
        run: |
          pwd
          cd /home/runner/work/got_auto/src
          python --version
          python run_daily_hof.py 6,7          
          
          
          
  run_89:
    # Name the Job
    name: run_89
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          GOTAUTH: ${{ secrets.GOTAUTH}}
        run: |
          cd ../../
          pwd
          git clone https://$GOTAUTH@github.com/brokenjade3000/got_auto.git
          cd got_auto
          chmod 775 ./script/install.sh
          ./script/install.sh
          
      # Runs the Super-Linter action
      - name: run_89
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
        run: |
          pwd
          cd /home/runner/work/got_auto/src
          python --version
          python run_daily_hof.py 8,9           
          
          

  run_1011:
    # Name the Job
    name: run_1011
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          GOTAUTH: ${{ secrets.GOTAUTH}}
        run: |
          cd ../../
          pwd
          git clone https://$GOTAUTH@github.com/brokenjade3000/got_auto.git
          cd got_auto
          chmod 775 ./script/install.sh
          ./script/install.sh
          
      # Runs the Super-Linter action
      - name: run_1011
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
        run: |
          pwd
          cd /home/runner/work/got_auto/src
          python --version
          python run_daily_hof.py 10,11
                   
