name: schedule_winterfall

# Run this workflow every time a new commit pushed to your repository
on:
  schedule:
    - cron: '35 18 * * 3'

jobs:


  job_1_3:
    # Name the Job
    name: job_2_5
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
     
          
      # Runs the Super-Linter action
      - name: run_2_5
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          SCHEDULE_TOKEN: ${{ secrets.SCHEDULE_TOKEN }}
        run: |
          curl -X POST -H "authorization: Bearer ${{ secrets.SCHEDULE_TOKEN }}" https://api.github.com/repos/brocjae/pub_hofs/dispatches -d '{"event_type":"join_winterfall","client_payload": {"id":",0,1,3,"}' 
