name: test_git

# Run this workflow every time a new commit pushed to your repository
on:
  workflow_dispatch
  
jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  run_23:
    # Name the Job
    name: run_23
    # Set the type of machine to run on
    runs-on: ubuntu-18.04
    timeout-minutes: 120

    steps:
      - name: Check out my other private repo
        uses: actions/checkout@v2
        with:
          repository: brokenjade3000/got_auto
          token: ${{ secrets.BK3K_TOKEN }} # `GH_PAT` is a secret that contains your PAT
          path: /home/runner/work/got_auto

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          GOTAUTH: ${{ secrets.GOTAUTH}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd

          
      # Runs the Super-Linter action
      - name: run_23
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOTAUTH: ${{ secrets.GOTAUTH}}
        run: |
          pwd
          ls
          python --version
          ls /home/runner/work/got_auto
